
mail:
  configs:
    # ук╨е
    - username: bookmanager_zjkj@163.com
      password: TUOEHWMMYZSKMUFK
      host: smtp.163.com
      port: 25
      protocol: smtp
      default-encoding: UTF-8
server:
  port: 9966
