server:
  port: 8892
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.103:3306/bookmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
