mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bookmanager.setting.model
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.bookmanager: debug
  file:
    path: log/blog-dev.log
spring:
  profiles:
    active: dev
  mail:
    configs:
      - host: smtp.163.com
        password: TUOEHWMMYZSKMUFK
        username: bookmanager_zjkj@163.com
        port: 465
        protocol: smtps
        default-encoding: utf-8
        properties:
          mail:
            smtp:
              auth: true
              timeout: 36000
              socketFactory:
                port: 465
                class: javax.net.ssl.SSLSocketFactory
              starttls:
                enable: true
                required: true
              ssl.enable: true

